env: local
paths:
  outcome: "../outputs/features500/outcomes/SIMVASTATIN/SIMVASTATIN.csv"
  exposure: "../outputs/features500/outcomes/SIMVASTATIN/SIMVASTATIN.csv"
  #output_path: "outputs/finetuning"
  run_name: "test"
  #tokenized_dir:"tokenized"
  tokenized_file: "tokenized_finetune.pt" # can also be a list
  tokenized_pids: "pids_finetune.pt" # can also be a list
  predefined_splits: ../outputs/pretraining/test/finetune_SIMVASTATIN_censored_1_hours_pre_SIMVASTATIN_followup_start_at_index_date_test
  #exclude_pids: outputs\pretraining\behrt_test\finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test\test_pids.pt

data:
  num_patients: 500 #300
  val_split: 0.1
  test_split: 0.1
  truncation_len: 20
  # gender: M
  min_age: 40
  max_age: 80
  # min_len: null
  #code_types:
   # - D
  min_len: 2
  # remove_features: ['abspos']
  # number_of_train_patients: 10


outcome: 
  n_hours_censoring: -1 # censor time after index date (negative means before)
  n_hours_start_follow_up: -1
  first_time_outcomes_only: false # only consider patients with no outcome before index date/ patient with outcome before index date are excluded
  censor_diag_end_of_visit: false
  n_hours_diag_censoring: 720
  # index_date: # if all patients should have the same censor date
    # year: 2015
    # month: 01
    # day: 01



  
  
 
