env: local
paths:
  model_path: "outputs/example_pretraining/example/finetune_EXAMPLE_OUTCOME_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_at_index_date_test"
  run_name: simulate_binary_outcome
  output: "outputs/example_features/outcomes/EXAMPLE_CENSOR_simulated_outcome"

simulation:
  _target_: ehr2vec.simulation.binary_outcome.tbehrt
  params: 
    a: 1
    b: .5
    c: .1
max_years: 3
days_offset: 1
  
  
