env: local
output_dir: outputs/example_features
tokenized_dir_name: "tokenized"
paths:
  run_name: "_test"
loader:
  # can provide formatted data or features
  data_dir:  example_data/synthea500 
  concepts: [
    diagnose,
    medication
  ]
  batch_size: 64
  chunksize: 300

features:
  age: 
    round: 2
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: True
  background: ['GENDER']

tokenizer:
  sep_tokens: false
  cls_token: true
  padding: false
  truncation: null
  additional_codes:
    - M308136
  # cutoffs:
   # D: 3 # diagnosis
   # M: 4 # medication

excluder:
  min_len: 2

split_ratios:
  pretrain: 0.72 # 80% of 90%
  finetune: 0.18 # 20% of 90%
  test: 0.1
handler:
  min_age: -1
  max_age: 120

# can be a list
# exclude_pids: 
# assigned_pids: 
  # can be a list
  # pretrain: 
  #  - 
# predefined_splits_dir: 

