env: local
paths:
  run_name: _example
outcomes_name: "EXAMPLE_OUTCOME"
features_dir: outputs/example_features
loader:
  data_dir: example_data/synthea500
  concepts: [
    diagnose,
    medication
  ]
  batch_size: 50
  chunksize: 300
outcomes:
  EXAMPLE_OUTCOME: 
    type: [CONCEPT]
    match: [['DT148XX']]
    exclude: ['DT148XX2']
    match_how: contains
    case_sensitive: true
  EXAMPLE_CENSOR:
    type: [CONCEPT]
    match: [['M314076']]
    match_how: startswith
    case_sensitive: false
    