env: local
project: "PHAIR"
paths:
  pretrain_model_path: "outputs/example_pretraining/example"
  outcome: "outputs/example_features/outcomes/EXAMPLE_OUTCOME/EXAMPLE_OUTCOME.csv"
  exposure: "outputs/example_features/outcomes/EXAMPLE_OUTCOME/EXAMPLE_CENSOR.csv"
  run_name: "test_stats"
  # tokenized_dir: "tokenized"
  tokenized_file: "tokenized_finetune.pt" # can also be a list
  tokenized_pids: "pids_finetune.pt" # can also be a list
  # predefined_splits: outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test_2
  # exclude_pids: outputs\pretraining\behrt_test\finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test\test_pids.pt
data:
  num_patients: 300 #300
  val_split: 0.1
  test_split: 0.1
  truncation_len: 30
  # gender: M
  min_age: 0
  max_age: 70
  # min_len: null
  min_len: 2
  number_of_train_patients: 10
  select_patient_group: null

model:
  behrt_embeddings: false

outcome: 
  n_hours_censoring: -24 # censor time after index date (negative means before)
  n_hours_start_follow_up: 100
  first_time_outcomes_only: False # only consider patients with no outcome before index date/ patient with outcome before index date are excluded
  # index_date: # if all patients should have the same censor date
    # year: 2015
    # month: 01
    # day: 01