env: local
project: "PHAIR"
paths:
  ps_model_path: "outputs/example_pretraining/example/finetune_EXAMPLE_CENSOR_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_1_hours_pre_index_date_run_test"
  outcome_model_path: "outputs/example_pretraining/example/finetune_EXAMPLE_CENSOR_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_1_hours_pre_index_date_run_test"
  run_name: simulate_outcome_from_emb
  output_path: "outputs/example_features/outcomes/EXAMPLE_CENSOR_simulated_outcome"

simulation:
  a: 1 # exposure coefficient
  b: .5 # treatment patient embeddings coefficient
  c: .1 # outcome patient embeddings coefficient
  d: .3 # intercept
  t_sparsity: 0.7 # proportion of treatment patient embeddings that will have zero coefficients
  o_sparsity: 0.7 # proportion of outcome patient embeddings that will have zero coefficients
  t_scale: 0.1 # scale of the normal distribution for treatment patient embeddings coefficients
  o_scale: 0.1 # scale of the normal distribution for outcome patient embeddings coefficients
max_years: 3
days_offset: 1
  
  
  
