env: local
project: &default_project PHAIR
run_name: &default_run_name test
wandb_kwargs:
  project: *default_project
  name: *default_run_name
  group: estimate_effect_binary
  job_type: test
  tags:
    - synthea 
    - local
    - ATE
    - test
    - double_robust

paths:
  ps_model_path: "outputs/example_pretraining/example/finetune_EXAMPLE_CENSOR_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_at_index_date_test"
  outcome: "outputs/example_features/outcomes/EXAMPLE_OUTCOME/EXAMPLE_OUTCOME.csv"
  # used for double-robust estimation:
  outcome_predictions: "outputs/example_pretraining/example/finetune_SIMULATED_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_at_index_date_test/predictions_and_targets.csv"
  outcome_predictions_counterfactual: "outputs/example_pretraining/example/finetune_SIMULATED_censored_24_hours_pre_EXAMPLE_CENSOR_followup_start_at_index_date_test/counterfactual_predictions_test/counterfactual_predictions.csv"
  output_path: "outputs/experiments/test"
  run_name: *default_run_name
ps_file: "predictions_and_targets.csv"
estimator:
  methods: ["AIPW", "IPW", "TMLE"]
  effect_type: "ATE"
  n_bootstrap: 30


