DEFAULT_BLOBSTORE = "CINF"
DEFAULT_N_SPLITS = 5  # You can change this to desired value
DEFAULT_VAL_SPLIT = 0.2

TREATMENT_COL = "treatment"
OUTCOME_COL = "outcome"
PS_COL = "ps"

COUNTERFACTUAL_TREATED_COL = "Y1_hat"
COUNTERFACTUAL_CONTROL_COL = "Y0_hat"
OUTCOME_PREDICTIONS_COL = "Y_hat"

