DEFAULT_BLOBSTORE = "CINF"
DEFAULT_N_SPLITS = 5  # You can change this to desired value
DEFAULT_VAL_SPLIT = 0.2

TREATMENT_COL = "treatment"
OUTCOME_COL = "outcome"
PS_COL = "ps"

CF_TREATED_COL = "Y1_hat"
CF_CONTROL_COL = "Y0_hat"
OUTCOME_PROBABILITY_COL = "Y_hat"

ORG_PID_COL = "pid"
PID_COL = "PID"

PROBA_COL = "proba"
TARGET_COL = "target"

TIMESTAMP_COL = "TIMESTAMP"

OUTCOME_TREATED_COL = "Y1"
OUTCOME_CONTROL_COL = "Y0"
