env: local
project: "PHAIR"
output_dir: /dtu/p1/kirkle/corebehrt_phair/features/synthea/100k
tokenized_dir_name: "tokenized"
paths:
  run_name: "synthea_100k"
loader:
  # can provide formatted data or features
  data_dir: /dtu/p1/kirkle/formatted_data/synthea/100k 
  concepts: [
    diagnose,
    medication
  ]
  batch_size: 25000
  chunksize: 50000

features:
  age: 
    round: 2
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: True
  background: ['GENDER']

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: null
  additional_codes: # atorvastatin
    - M617312 
    - M617311
    - M617310
    - M617320
    - M259255

  # cutoffs:
   # D: 3 # diagnosis
   # M: 4 # medication

excluder:
  min_len: 1

split_ratios:
  pretrain: 0.72 # 80% of 90%
  finetune: 0.18 # 20% of 90%
  test: 0.1

handler:
  min_age: 0
  max_age: 120

exposure_patterns: # atorvastatin
  - M617312
  - M617311
  - M617310
  - M617320
  - M259255
  # Add more patterns as needed
# can be a list
# exclude_pids: 
# assigned_pids: 
  # can be a list
  # pretrain: 
  #  - 
# predefined_splits_dir: 

