env: local
project: "PHAIR"
paths:
  run_name: exposure
outcomes_name: "EXPOSURE"
features_dir: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea/100k
loader:
  data_dir: /dtu/p1/kirkle/PHAIR_project/formatted_data/synthea/100k
  concepts: [
    medication
  ]
  batch_size: 20000
  chunksize: 50000
outcomes:
  amlodipine:
    type: [CONCEPT]
    match: [[M898353, M898350, M898356, M898342, M898359, M308136]]
    match_how: startswith
    case_sensitive: false
    
