env: local
run_name: &default_run_name run_00
project: &default_project "PHAIR"

wandb_kwargs:
  project: *default_project
  group: finetuning_simulated_outcome_amlodipine_a_4_b_0
  job_type: full
  # name: *default_run_name
  tags:
    - 40_to_80
    - synthea
    - 100k
    - simulated_outcome

paths:
  pretrain_model_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_02
  # model_path: # can provide ft model path
  # checkpoint_epoch: 1
  outcome: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea_0712/100k/outcomes/amlodipine_random_80/simulated_outcome_a_4p0_b_0p0/SIMULATED.csv
  exposure: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea_0712/100k/outcomes/EXPOSURE/amlodipine_80.csv
  # output_path: "outputs/finetuning"
  run_name: *default_run_name
  # tokenized_dir:"tokenized"
  tokenized_file: "tokenized_finetune.pt" # can also be a list
  tokenized_pids: "pids_finetune.pt" # can also be a list
  predefined_splits: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_02/finetune_amlodipine_80_censored_30_days_pre_amlodipine_80_followup_start_at_index_date_run_00
  # exclude_pids: outputs\pretraining\behrt_test\finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test\test_pids.pt

model:
  pool_type: "gru"
  bidirectional: true
  # extend_head: 
  # hidden_size: null

data:
  # num_patients: 300 #300
  val_split: 0.2
  test_split: 0.0
  truncation_len: 512
  # gender: M
  min_age: 40
  max_age: 80
  # min_len: null
  # code_types:
   # - D
  min_len: 5
  # remove_features: ['abspos']

calibration: "isotonic"

outcome: 
  n_hours_censoring: -720 # censor time after index date (negative means before)
  n_hours_start_follow_up: 1 # At index date
  first_time_outcomes_only: false # only consider patients with no outcome before index date/ patient with outcome before index date are excluded
  control_code: PLACEHOLDER_1 # code to be used for "no exposure"
  keep_codes: [M898353, M898350, M898356, M898342, M898359, M308136, PLACEHOLDER_1] # list of regex to not censor (first occurence is kept) # use ^exactmatch$ for exact matches
trainer_args:
  sampler: true
  sample_weight_function:
    _target_: ehr2vec.evaluation.utils.inverse_sqrt # function to calculate sample weights
  sample_weight_multiplier: 1 # adjust the sampling weight of the positive class (1 is balanced)
  pos_weight: null # weight for positive class in the loss
  batch_size: 512
  val_batch_size: 512
  effective_batch_size: 512
  epochs: 100
  info: true
  gradient_clip: 
    clip_value: 1.0
  mixed_precision: false
  shuffle: true
  checkpoint_frequency: 1
  early_stopping: 15
  stopping_criterion: roc_auc
  
optimizer:
  lr: 1e-5
  eps: 1e-6

scheduler:
  _target_: transformers.get_constant_schedule_with_warmup
  num_warmup_epochs: 5  

metrics:
  roc_auc:
    _target_: ehr2vec.evaluation.metrics.ROC_AUC
  pr_auc:
    _target_: ehr2vec.evaluation.metrics.PR_AUC
  balanced_accuracy:
    _target_: ehr2vec.evaluation.metrics.Balanced_Accuracy
  precision:
    _target_: ehr2vec.evaluation.metrics.Precision
  recall:
    _target_: ehr2vec.evaluation.metrics.Recall
  

