env: local
project: "PHAIR"
paths:
  model_path: /dtu/p1/kirkle/corebehrt_phair/pretrain/run_01/finetune_EXPOSURE_censored_1_hours_pre_EXPOSURE_followup_start_at_index_date_ft_exposure
  run_name: simulate_binary_outc
  output: /dtu/p1/kirkle/corebehrt_phair/features/synthea/100k/outcomes/EXPOSURE_simulated_outcome/

simulation:
  _target_: ehr2vec.simulation.binary_outcome.tbehrt
  params: 
    a: 1
    b: .5
    c: .1
max_years: 10
days_offset: 1
  
  
  
