env: local
project: "PHAIR"
paths:
  model_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_01_continue/finetune_SIMULATED_censored_4_days_pre_EXPOSURE_followup_start_at_index_date_run_04
  run_name: calibrated_run_04

model:
  pool_type: "gru"
  bidirectional: true

data:
  truncation_len: 512
  counterfactual: # can be a list of regexes
    exposure_regex:
    - M617312 
    - M617311
    - M617310
    - M617320
    - M259255
      
calibration: isotonic

tester_args:
  batch_size: 512
  val_batch_size: 512
  info: true
  shuffle: true


  
  
 
