env: local
project: "PHAIR"
paths:
  model_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_02/finetune_amlodipine_80_censored_30_days_pre_amlodipine_80_followup_start_at_index_date_run_00
  run_name: simulate_binary_outcome
  output_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea_0712/100k/outcomes/amlodipine_random_80/simulated_outcome_a_4p0_b_0p0/
predictions_file: predictions_and_targets_calibrated_isotonic.csv
simulation:
  _target_: ehr2vec.simulation.binary_outcome.tbehrt # a * exposure + b * (ps + c)
  params: 
    a: 4
    b: 0 #2
    c: -2
max_years: 10 # max time after index date to simulate outcome
days_offset: 1 # earliest time of outcome after index date
  
  
  
