env: local
project: &default_project "PHAIR"
run_name: &default_run_name strength
paths:
  ps_model_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_01_continue/finetune_amlodipine_censored_10_hours_pre_amlodipine_followup_start_at_index_date_run_05
  
  outcome: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea/100k/outcomes/amlodipine_simulated_outcome_a_0p0/SIMULATED.csv
  counterfactual_outcome: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/features/synthea/100k/outcomes/amlodipine_simulated_outcome_a_0p0/COUNTERFACTUAL.csv

  outcome_predictions: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_01_continue/finetune_SIMULATED_censored_1_hours_post_amlodipine_followup_start_at_index_date_0p0/predictions_and_targets.csv
  outcome_predictions_counterfactual: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/pretrain/run_01_continue/finetune_SIMULATED_censored_1_hours_post_amlodipine_followup_start_at_index_date_0p0/predictions_and_targets.csv
  
  output_path: /dtu/p1/kirkle/PHAIR_project/corebehrt_phair/effect_estimation/synthea/100k/simulated_outcome/effect_strength/effect_strength_a_x_b_2p0_c_neg2p0_improved_counterfactual
  run_name: *default_run_name
ps_file: predictions_and_targets_calibrated_isotonic.csv

#   num_patients: 10000

estimator:
  methods: ["IPW", "AIPW", "TMLE"]
  effect_type: "ATE"
  n_bootstrap: 100
  common_support_threshold: 0.01

wandb_kwargs:
  project: *default_project
  name: *default_run_name
  group: estimate_effect_binary_strength_a_x_b_2p0_c_neg2p0_improved_counterfactual
  job_type: full
  tags:
    - synthea 
    - 100k
    - ATE
    - effect_strength_a_x_b_2p0_c_neg2p0_improved_counterfactual
    - simulated_outcome
