env: local
paths:
  run_name: test
outcomes_name: "SIMVASTATIN"
features_dir: outputs/example_features
loader:
  data_dir: example_data/synthea500
  concepts: [
    medication
  ]
  batch_size: 1000
  chunksize: 5000
outcomes:
  SIMVASTATIN: 
    type: [CONCEPT]
    match: [['M312961']]
    match_how: contains
    case_sensitive: true
  
    