# This workflow will install Python dependencies and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Lint using flake8 
on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install flake8>=6.1.0
    - name: Lint with flake8
      run: |
        # Check syntax errors
        flake8 ehr2vec tests --count --select=E9,F63,F7,F82,U100,E711,E712,E713,E714,E721,F401,F402,F405,F811,F821,F822,F823,F831,F841,F901, --exclude ehr2vec\azure_run,ehr2vec\main\estimate_causal_effect.py  
