name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: Activate venv
              run: |
                source .venv/bin/activate

            - name: main.create_data
              run: |
                python -m ehr2vec.main.create_data
            
            - name: main.pretrain
              run: |
                python -m ehr2vec.main.pretrain
            
            - name: main.create_outcomes
              run: |
                python -m ehr2vec.main.create_outcomes
            
            - name: main.simulate_binary_outcome
              run: |
                python -m ehr2vec.main.simulate_binary_outcome

            - name: main.finetune_cv
              run: |
                python -m ehr2vec.main.finetune_cv

            - name: main.finetune_cv
              run: |
                python -m ehr2vec.main.finetune_cv --config_path finetune_simulated_example
            
            
