name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: main.create_data
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.create_data
                
            
            - name: main.pretrain
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.pretrain
            
            - name: main.create_outcomes
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.create_outcomes
            
            - name: main.finetune_cv
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.finetune_cv
            
            - name: main.finetune_cv_evaluate
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.finetune_cv_evaluate 
            
            - name: main.simulate_binary_outcome
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.simulate_binary_outcome

            - name: main.finetune_cv
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.finetune_cv --config_path finetune_simulated_example

            - name: main.estimate_causal_effect
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.estimate_causal_effect

            - name: main.estimate_causal_effect
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.estimate_causal_effect --config_path estimate_effect_binary_example_counterfactual

             
            
            
