name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: create_data
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.01_create_data
                
            
            - name: pretrain
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.02_pretrain
            
            - name: create_outcomes_and_exposures
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.03_create_outcomes
            
            - name: finetune_cv
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.04_finetune_cv

            - name: feature_importance_perturb
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.05_feature_importance_perturb

            - name: evaluate_cv
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.05_cv_evaluate 
            
            - name: simulate_binary_outcome
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.05_simulate_binary_outcome

            - name: finetune_on_simulated_outcomes
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.04_finetune_cv --config_path example_configs/05_02_finetune_simulated.yaml

            - name: estimate_causal_effect
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.06_estimate_causal_effect

            - name: estimate_causal_effect_counterfactual_simulation
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.06_estimate_causal_effect --config_path example_configs/06_estimate_effect_binary_counterfactual.yaml

            - name: predict_counterfactual
              run: |
                source .venv/bin/activate  
                python -m ehr2vec.main.05_predict_counterfactual
            

             
            
            
