name: Pylance Check

on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]

jobs:
  pylance-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylance pyright

    - name: Run Pylance
      run: |
        pyright $(find . -name "*.py" ! -path "*/notebooks/*" ! -path "*/.ipynb_checkpoints/*")

    - name: Check for Pylance errors
      run: |
        if [ -f pylance-results.txt ]; then
          if grep -q "error" pylance-results.txt; then
            echo "Pylance found errors:"
            cat pylance-results.txt
            exit 1
          else
            echo "No Pylance errors found."
          fi
        else
          echo "Pylance results file not found."
          exit 1
        fi